# Compose file file format
# Pay attention to https://bom.so/kVr7Qn
version: '3.8'

services: 
  classify_toxic_text:
    # The name will be displayed in docker ps
    container_name: classify_toxic_text
    # Build the image from Dockerfile
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:30000'
    image: khoav1371999/classify_toxic_text:0.0.1
