apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: monitoring
  annotations:
      prometheus.io/scrape: 'true'
      prometheus.io/port:   '3000'
spec:
  selector:
    app: {{ .Release.Name }}
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30000
